version: '3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    expose:
      - "5959"
    ports:
      - "5959:5959"
    command: -e 'input { tcp {  port => 5959  codec => json   } } output { stdout {} }'
    
  web:
    build: .
    ports:
      - "8000:80"
    links:
      - logstash
    
